/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

//////////////IL FAUT METTRE : GRIL
import Controleur.Controleur;
import Controleur.Message;
import Controleur.Observe;
import Controleur.TypesMessages;
import Modele.Aventurier;
import Modele.Carte_Tirage_Tresor;
import Util.Parameters;
import static Util.Utils.TypeCarteTresor.*;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.border.LineBorder;
//JOUEURS + CHOIX(DEPLACER, ASSECHER, CS)
//NIVEAU EAU

/**
 *
 * @author vialjule
 */
public class VuePlateauJoueur extends Observe {

    private Controleur controleur;
    private JFrame fenetre;
    private VueGrille plateau;
    private int btn5Etat = 0; //0: terminer tour 1: annuler
    private int etatAnnuler;

    /**
     * Creates new form IHM1
     */
    public VuePlateauJoueur(Controleur controleur) {
        fenetre = new JFrame("L'île interdite");
        this.controleur = controleur;
        initComponents();
        VueNiveau vueNiveau = new VueNiveau(1);
        jPanel3.setLayout(new BorderLayout());
        plateau = new VueGrille(this);
        jPanel3.add(plateau.getPanelBody(), BorderLayout.CENTER);
        jPanel4.setLayout(new BorderLayout());
        jPanel4.add(vueNiveau);
        fenetre.setVisible(true);

        jButton13.setText("      ");
        jButton14.setText("      ");
        jButton15.setText("      ");
        jButton16.setText("      ");
        jButton17.setText("      ");
        jButton18.setText("      ");
        jButton19.setText("      ");
        updateCartesJoueurs(controleur.getJoueurCourant());
        cartesSpeciales();
    }

    public void updatePlateauJoueur() {
        jLabel1.setText(controleur.getJoueurCourant().getNom());
        jPanel3.removeAll();
        plateau = new VueGrille(this);
        jPanel3.add(plateau.getPanelBody(), BorderLayout.CENTER);
        String str = Integer.toString(controleur.getPA());
        jLabel3.setText(str);
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
        jButton5.setText("TERMINER TOUR");
        plateau.addObservateur(controleur);
        updateCartesJoueurs(controleur.getJoueurCourant());
        removeActions();
        cartesSpeciales();
    }

    public Controleur getControleur() {
        return controleur;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();

        fenetre.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel21.setText("               L'île");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 882, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(371, 371, 371)
                                .addComponent(jLabel21)
                                .addContainerGap(647, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("NomJoueur");

        jButton1.setText("Se déplacer");
        jButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jButton1ActionPerformed(e);
            }
        });

        jButton2.setText("Assécher une tuile");
        jButton2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jButton2ActionPerformed(e);
            }
        });

        jButton3.setText("Echanger");

        jButton4.setText("Prendre trésor");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Points d'action : ");
        int nbPA = controleur.getPA();
        String str = Integer.toString(nbPA);
        jLabel3.setText(str);

        jButton5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton5.setText("TERMINER TOUR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Cartes :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addContainerGap())
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(jLabel4)
                                                                .addComponent(jButton16)
                                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                        .addComponent(jButton15)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jButton19))
                                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                        .addComponent(jButton14)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jButton18))
                                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                        .addComponent(jButton13)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jButton17))
                                                                .addComponent(jLabel1)
                                                                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                        .addGap(108, 108, 108)
                                                                )
                                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                        .addComponent(jLabel2)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(jLabel3)))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                )
                                                                .addGap(108, 108, 108)
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING))))
                                                .addGap(0, 13, Short.MAX_VALUE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jButton2))
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton13)
                                        .addComponent(jButton17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton14)
                                        .addComponent(jButton18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton15)
                                        .addComponent(jButton19))
                                .addGap(10, 10, 10)
                                .addComponent(jButton16)
                                .addGap(18, 18, 18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(fenetre.getContentPane());
        fenetre.getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        fenetre.pack();
    }// </editor-fold>                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
        if (btn5Etat == 0) {
            Message m = new Message();
            m.type = TypesMessages.TERMINER_TOUR;
            notifierObservateur(m);
        } else if (btn5Etat == 1) {
            Message m = new Message();
            m.type = TypesMessages.ANNULER_ACTION;
            notifierObservateur(m);
        }
    }

    public VueGrille getPlateau() {
        return plateau;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        Message m = new Message();
        m.type = TypesMessages.CHOISIR_SE_DEPLACER;
        m.casJeu = 0;
        notifierObservateur(m);
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        Message m = new Message();
        m.type = TypesMessages.CHOISIR_ASSECHER;
        m.casJeu = 1;
        notifierObservateur(m);
    }

    // Methodes
    public void setNomJoueur(String nomJoueur) {
        jLabel1.setText(nomJoueur);
    }

    public void setBtn5Etat() {
        if (btn5Etat == 0) {
            btn5Etat = 1;
        } else {
            btn5Etat = 0;
        }
    }

    public void quandSeDeplacer() {
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jButton5.setText("ANNULER");
    }

    public void tourTerminé() {
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jButton5.setText("Terminer Tour");
    }

    public void updateCartesJoueurs(Aventurier joueur) {
        ArrayList<Carte_Tirage_Tresor> inventaire = controleur.getJoueurCourant().getInventaire();
        ArrayList<JButton> jButtons = new ArrayList<>();
        jButtons.add(jButton13);
        jButtons.add(jButton14);
        jButtons.add(jButton15);
        jButtons.add(jButton16);
        jButtons.add(jButton17);
        jButtons.add(jButton18);
        jButtons.add(jButton19);

        // METTRE LES BOUTONS HELICO/SACS DANS SON INVENTAIRE ENABLED
        for (int i = 0; i < inventaire.size(); i++) {
            jButtons.get(i).setVisible(true);
            jButtons.get(i).setText(inventaire.get(i).getType().toString());
            if (inventaire.get(i).getType() != HELICOPTERE && inventaire.get(i).getType() != SAC_DE_SABLE) {
                jButtons.get(i).setEnabled(false);
            } else {
                jButtons.get(i).setEnabled(true);
            }
        }
        // METTRES LES BOUTONS VISIBLES QUAND IL Y A UNE CARTE
        for (int i = inventaire.size(); i < jButtons.size(); i++) {
            jButtons.get(i).setVisible(false);
        }
    }

    public void cartesSpeciales() {
        // AJOUTER ACTION LISTENER AUX BOUTONS
        ArrayList<Carte_Tirage_Tresor> inventaire = controleur.getJoueurCourant().getInventaire();
        ArrayList<JButton> jButtons = new ArrayList<>();
        jButtons.add(jButton13);
        jButtons.add(jButton14);
        jButtons.add(jButton15);
        jButtons.add(jButton16);
        jButtons.add(jButton17);
        jButtons.add(jButton18);
        jButtons.add(jButton19);

        for (int i = 0; i < inventaire.size(); i++) {

            if (inventaire.get(i).getType() == HELICOPTERE) {
                Carte_Tirage_Tresor carteTresor = inventaire.get(i);
                jButtons.get(i).addActionListener((ActionEvent e) -> {
                    System.out.println("HELICO action msg");
                    Message m = new Message();
                    m.type = TypesMessages.CARTE_ACTION;
                    m.casJeu = 0;
                    m.carte = carteTresor;
                    notifierObservateur(m);
                });

            } else if (inventaire.get(i).getType() == SAC_DE_SABLE) {
                Carte_Tirage_Tresor carteTresor = inventaire.get(i);
                jButtons.get(i).addActionListener((ActionEvent e) -> {
                    System.out.println("SAC action msg");
                    Message m = new Message();
                    m.type = TypesMessages.CARTE_ACTION;
                    m.casJeu = 1;
                    m.carte = carteTresor;
                    notifierObservateur(m);
                });
            }
        }
    }

    public void removeActions() {
        ArrayList<JButton> jButtons = new ArrayList<>();
        jButtons.add(jButton13);
        jButtons.add(jButton14);
        jButtons.add(jButton15);
        jButtons.add(jButton16);
        jButtons.add(jButton17);
        jButtons.add(jButton18);
        jButtons.add(jButton19);

        for (int i = 0; i < jButtons.size(); i++) {
            for (ActionListener al : jButtons.get(i).getActionListeners()) {
                jButtons.get(i).removeActionListener(al);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueInscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueInscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueInscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueInscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration                   
}
